#                                                                        #
# Default subroutes configuration for the Debug.Toolbar package          #
#                                                                        #
#
# Include them to your project by adding the following snippet *above* other
# route definitions in the main Routes.yaml:
#
#-
#  name: 'DebugToolbar'
#  uriPattern: '<DebugToolbarSubroutes>'
#  subRoutes:
#    'DebugToolbarSubroutes':
#      package: Debug.Toolbar

-
  name: 'Profiles'
  uriPattern: 'debug/profile'
  appendExceedingArguments: true
  defaults:
    '@action':      'index'
    '@package':     'Debug.Toolbar'
    '@controller':  'Profile'
    '@format':      'html'

-
  name: 'Profile'
  uriPattern: 'debug/profile/{token}'
  appendExceedingArguments: true
  defaults:
    '@action':      'index'
    '@package':     'Debug.Toolbar'
    '@controller':  'Profile'
    '@format':      'html'

-
  name: 'Profile with Renderer'
  uriPattern: 'debug/profile/{token}/{renderer}'
  appendExceedingArguments: true
  defaults:
    '@action':      'index'
    '@package':     'Debug.Toolbar'
    '@controller':  'Profile'
    '@format':      'html'

-
  name: 'Profiles'
  uriPattern: 'debug/profile-test'
  appendExceedingArguments: true
  defaults:
    '@action':      'test'
    '@package':     'Debug.Toolbar'
    '@controller':  'Profile'
    '@format':      'html'