Debug:
  Profiling:
    Classes: []

TYPO3:
  Flow:
    persistence:
      doctrine:
        sqlLogger: Debug\Toolbar\Logger\SqlLogger
    # error:
    #   exceptionHandler:
    #     className: 'Debug\Toolbar\Error\DebugExceptionHandler'

    http:
      chain:

        'postprocess':
          chain:
            'toolbar':
              position: 'end'
              component: 'Debug\Toolbar\Http\ToolbarComponent'