Debug:
  Profiling:
    Classes: []

TYPO3:
  Flow:
    persistence:
      doctrine:
        sqlLogger: 'Debug\Toolbar\Logger\SqlLogger'

    http:
      chain:
        'process':
          chain:
            'initdebugging':
              position: 'before dispatching'
              component: 'Debug\Toolbar\Http\InitComponent'

        'postprocess':
          chain:
            'toolbar':
              position: 'end'
              component: 'Debug\Toolbar\Http\ToolbarComponent'