Debug:
  Profiling:
    Classes: []

TYPO3:
  FLOW3:
    persistence:
      doctrine:
        sqlLogger: Debug\Toolbar\Logger\SqlLogger
    #error:
    #  exceptionHandler:
    #    className: 'Debug\Toolbar\Error\DebugExceptionHandler'